### ISSUE TITLE
Feature request: Chrome-like incognito icons

### ISSUE THREAD

**Issue by Aleksandra0056** [schilkyl/incognito-indicator#1]
It would be good, if there would be option to set Chrome-like incognito icons

Images:
Chrome legacy:
![Chrome legacy Incognito mode icon](https://user-images.githubusercontent.com/69351811/218071232-dcb46bf3-87c4-49f5-aba9-4cb6f4f89ebb.jpg)
Chrome:
![Chrome Incognito mode icon](https://user-images.githubusercontent.com/69351811/218071262-ae65aaf7-e56c-46a6-8973-dcb105fd9051.png)

**Comment by SeaNettleStudios** [comment]
added chrome icons in #4
