### ISSUE TITLE
Feature request: Opera-like incognito icons

### ISSUE THREAD

**Issue by Aleksandra0056** [schilkyl/incognito-indicator#2]
I would also like the Opera-like incognito icons.

Opera legacy:
![Opera legacy incognito mode icon](https://user-images.githubusercontent.com/69351811/218071757-0432dc72-d51e-4923-9d53-76b5217b2129.png)
Opera:
![Opera incognito mode icon](https://user-images.githubusercontent.com/69351811/218071780-c5c1fa3b-078d-438d-bbe6-cd54d0e325fe.png)
Opera GX:
![Opera GX incognito mode icon](https://user-images.githubusercontent.com/69351811/218072573-59811118-7341-4274-800d-8435ed2aa2b7.jpg)

**Comment by SeaNettleStudios** [comment]
added opera icons in #4
