### ISSUE TITLE
Upgrade to Manifest v3

### ISSUE THREAD

**Issue by Aleksandra0056** [schilkyl/incognito-indicator#3]
The extension manifest version is slowly being outdated, so it would be great if you upgrade to Manifest v3 (Mozilla Firefox supports Manifest v3 from version v109.0).

**Comment by SeaNettleStudios** [comment]
This is on my radar. I decided to hold off on the work for now because v3 of the manifest is still churning between the browser vendors. I'll wait for the dust to settle before I migrate to v3.
